services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql 
    networks:
      - prestashop_network
  prestashop:
    build: .
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8083:443
    env_file: .env
    environment:
      DB_SERVER: mysql
      PS_INSTALL_AUTO: 0
    networks:
      - prestashop_network
networks:
    prestashop_network:
volumes:
  dbdata:
