<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHysqwcb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHysqwcb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHysqwcb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHysqwcb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHysqwcb\appProdProjectContainer([
    'container.build_hash' => 'Hysqwcb',
    'container.build_id' => '8d44fa78',
    'container.build_time' => 1733491560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHysqwcb');
