<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR75qnhh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR75qnhh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR75qnhh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR75qnhh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR75qnhh\appProdProjectContainer([
    'container.build_hash' => 'R75qnhh',
    'container.build_id' => '197e0f88',
    'container.build_time' => 1732996601,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR75qnhh');
